FIT5042_Ass2-war/src/java/com/xiaolong/fit5042/ass2/control/BooksController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.xiaolong.fit5042.ass2.control;

import com.xiaolong.fit5042.ass2.ejb.BookBean;
import com.xiaolong.fit5042.ass2.entities.Book;
import com.xiaolong.fit5042.ass2.entities.Comments;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author Xiaolong
 */
@ManagedBean
@SessionScoped
public class BooksController implements Serializable {

    @EJB
    BookBean bookBean;
    
    private Book book;
    private String searchTag;
    private List<Book> searchBookList;
    
    
    public BooksController() {}

    public List<Book> getSearchBookList() {
        return searchBookList;
    }

    public void setSearchBookList(List<Book> searchBookList) {
        this.searchBookList = searchBookList;
    }
    
    public String getSearchTag() {
        return searchTag;
    }

    public void setSearchTag(String searchTag) {
        this.searchTag = searchTag;
    }
    
    public Book getBook()
    {
        return book;
    }
    
    public String read(Book book)
    {
        this.book = book;
        return "book";
    }
    
    public String setupCreate()
    {
        book = new Book();
        return "book";
    }
    
    public String create()
    {
        bookBean.createBook(book);
        return "index";
    }
    
    public String update()
    {
        bookBean.updateBook(book);
        return "index";
    }
    
    public String delete(Book news)
    {
        bookBean.deleteBook(news);
        return "index";
    }
    
    public List<Book> getBookList()
    {
        return bookBean.findAllBook();
    }
    //return at most 5 news
    public List<Book> getLatestBooks()
    {
        ArrayList<Book> latestBook = new ArrayList<>();
        List<Book> bookList = bookBean.findAllBook();
        int size = bookList.size();
        if(size >=3 )
        {
            for(int x = 1; x <=3 ; x++)
            {
                latestBook.add(bookList.get(size-x));
            }
        }
        else
        {
            for(int x = size-1; x>=0 ; x--)
            {
                latestBook.add(bookList.get(x));
            }
        }      
        return latestBook;
    } 
    
    public String searchBooksByTitle()
    {
        bookBean.setSearchTitle(searchTag.toLowerCase().trim());
        searchBookList = bookBean.findByTitle();
        return "booklist";
    }
    public String allComments()
    {
        String result = "";
        Collection<Comments> com = book.getCommentList();
        if(com.size() > 0){
            for(Comments c: com)
            {
                result += c.getUserid().getUserName();
                result += ": /n";
                result += c.getMessage();
                result += "/n/n";
            }
        }
        else
        {
            result = "There is no comment for this book...\n Write one!";           
        }
        return result;
    }
}

FIT5042_Ass2-war/src/java/com/xiaolong/fit5042/ass2/control/NewsController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.xiaolong.fit5042.ass2.control;

import com.xiaolong.fit5042.ass2.ejb.NewsBean;
import com.xiaolong.fit5042.ass2.entities.News;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 *
 * @author Xiaolong
 */
@ManagedBean
@SessionScoped
public class NewsController implements Serializable{
    @EJB
    NewsBean newsBean;
    
    private News news;
    
    public NewsController() {}
    
    public News getNews()
    {
        return news;
    }
    
    public String read(News news)
    {
        this.news = news;
        return "news";
    }
    
    public String setupCreate()
    {
        news = new News();
        return "news";
    }
    
    public String create()
    {
        newsBean.createNews(news);
        return "index";
    }
    
    public String update()
    {
        newsBean.updateNews(news);
        return "index";
    }
    
    public String delete(News news)
    {
        newsBean.deleteNews(news);
        return "index";
    }
    
    public List<News> getNewsList()
    {
        return newsBean.findAllNews();
    }
    //return at most 5 news
    public List<News> getLatestNews()
    {
        ArrayList<News> latestNews = new ArrayList<>();
        List<News> newsList = newsBean.findAllNews();
        int size = newsList.size();
        if(size >=5 )
        {
            for(int x = 1; x <=5 ; x++)
            {
                latestNews.add(newsList.get(size-x));
            }
        }
        else
        {
            for(int x = size-1; x>=0 ; x--)
            {
                latestNews.add(newsList.get(x));
            }
        }      
        return latestNews;
    }
    
}

FIT5042_Ass2-war/web/book.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>#{booksController.book.title}</title>
        <link href="resource/css/style.css" rel="stylesheet" type="text/css"/>
    </h:head>
    <h:body>
        <h:form class="headForm">
            <div class="headDiv">
                <span>
                    <img src="resource/image/logo_monash_s.jpg" alt="Image Not Found!" class="logo"></img>
                </span>
                <span>
                    <p class="logSpan">this is a span</p>
                </span>
            </div>
            <hr />
            <div class="homeBook_pic"><img src="#{booksController.book.coverUrl}" alt="Not Found"/></div>
            <div class="homeBook_info">
                <strong>Title:</strong><br />
                <h:outputText value="#{booksController.book.title}"/><br/>
                <strong>Edition:</strong><br />
                <h:outputText value="#{booksController.book.edition}"/><br />
                <strong>Publish Year:</strong><br />
                <h:outputText value="#{booksController.book.publishYear.month}-#{booksController.book.publishYear.day}-#{booksController.book.publishYear.year + 1900}" />
                <br />
                <strong>Author:</strong> <br />
                <ui:repeat value="#{booksController.book.authors}" var="authorVar" varStatus="status">
                    <h:outputText value=" | " />
                    <h:outputText value="#{authorVar.name}"/>                       
                </ui:repeat>
                <br />
                <strong>Publisher:</strong><br />
                <h:outputText value="#{booksController.book.publisher}"/>               
            </div>
            <div class="commentsDiv">
                <strong>Comments:</strong><br />
                <h:outputText value="#{booksController.allComments()}" class="commentArea" />
            </div>
            <hr />
            <div>
                <h:outputText value="There are #{booksController.book.bookins.size()} books in our library:" /><br />
                <h:dataTable value="#{booksController.book.bookins}" var="insItem"
                             cellspacing="0px" cellpadding="3px" frame="border"
                             headerClass="insColumn">
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="ID" />
                        </f:facet>
                        <h:outputText value="#{insItem.id}" />
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Title" />
                        </f:facet>
                        <h:outputText value="#{booksController.book.title}" />
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Location" />
                        </f:facet>
                        <h:outputText value="#{insItem.location}" />
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="State" />
                        </f:facet>
                        <h:outputText value="#{insItem.insState}" />
                    </h:column>
                    <h:column>
                        <f:facet name="header">
                            <h:outputText value="Action" />
                        </f:facet>
                        <h:commandButton value="Loan" />
                    </h:column>
                    <hr />
                </h:dataTable>
            </div>
        </h:form>
    </h:body>
</html>

FIT5042_Ass2-war/web/booklist.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
        <link href="resource/css/style.css" rel="stylesheet" type="text/css"/>
    </h:head>
    <h:body>
        <h:form>
        <div>
            <ui:repeat value="#{booksController.searchBookList}" var="bookitem" varStatus="status">
                        <div>
                            <h:outputText value="#{bookitem.title}"/><br/>
                            <ui:repeat value="#{bookitem.authors}" var="authorVar" varStatus="status">
                                <h:outputText value=" | " />
                                <h:outputText value="#{authorVar.name}"/>                       
                            </ui:repeat>
                            <br />
                            <img src="#{bookitem.coverUrl}" alt="Not Found"/>
                        </div>
            </ui:repeat>
        </div>
        </h:form>
    </h:body>
</html>

FIT5042_Ass2-war/web/category.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
    </h:body>
</html>

FIT5042_Ass2-war/web/comment.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
    </h:body>
</html>

FIT5042_Ass2-war/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
        <link href="resource/css/style.css" rel="stylesheet" type="text/css"/>
    </h:head>
    <h:body>
        <h:form class="headForm">
            <div class="headDiv">
                <span>
                    <img src="resource/image/logo_monash_s.jpg" alt="Image Not Found!" class="logo"></img>
                </span>
                <span>
                    <p class="logSpan">this is a span</p>
                </span>
            </div>
            <div>
                <table>
                    <tr>
                        <td class="navTab">Category</td>
                        <td class="navTab">2222</td>
                        <td class="navTab">333333</td>
                    </tr>
                </table>
            </div>
            <div class="homeNewsDiv">
                <div class="homeHoursDiv">
                    <strong>Open Hours</strong><br/><br/>
                    Sun: 09:00 a.m. -- 10:00 p.m.<br/>
                    Mon: 07:00 a.m. -- 11:59 p.m.<br/>
                    Tue: 07:00 a.m. -- 11:59 p.m.<br/>
                    Wen: 07:00 a.m. -- 11:59 p.m.<br/>
                    Thu: 07:00 a.m. -- 11:59 p.m.<br/>
                    Fri: 07:00 a.m. -- 09:00 p.m.<br/>
                    Sat: 09:00 a.m. -- 10:00 p.m.<br/>
                </div>
                <div class="homeNewsList">
                    News:<br />
                    <ui:repeat value="#{newsController.latestNews}" var="newsitem" varStatus="status">
                        <div>
                            <h:outputText value="#{newsitem.title}"/><br/>
                            <h:outputText value="#{newsitem.message}" /><br/>                         
                        </div>
                    </ui:repeat>
                </div>                   
            </div>
            <div class="homeBookDiv">
                <div class="homeSearch">
                    <h:inputText id="searchTag" title="search..." class="homeSearchText"
                           value="#{booksController.searchTag}" required="true" 
                           requiredMessage="Search cannot be blank"/>
                    <h:commandButton id="searchBt" value ="Search"
                           action="#{booksController.searchBooksByTitle()}"/>
                </div>
                <div class="homeBookList">
                    <ui:repeat value="#{booksController.latestBooks}" var="bookitem" varStatus="status">
                        <div class="homeBook">
                            <div class="homeBook_pic"><img src="#{bookitem.coverUrl}" alt="Not Found"/></div>
                            <div class="homeBook_info">
                                <strong>Title:</strong><br />
                                <h:outputText value="#{bookitem.title}"/><br/>
                                <strong>Edition:</strong><br />
                                <h:outputText value="#{bookitem.edition}"/><br />
                                <strong>Publish Year:</strong><br />
                                <h:outputText value="#{bookitem.publishYear.month}-#{bookitem.publishYear.day}-#{bookitem.publishYear.year + 1900}" />
                                <br />
                                <strong>Author:</strong> <br />
                                <ui:repeat value="#{bookitem.authors}" var="authorVar" varStatus="status">
                                    <h:outputText value=" | " />
                                    <h:outputText value="#{authorVar.name}"/>                       
                                </ui:repeat>
                                <br />
                                <strong>Publisher:</strong><br />
                                <h:outputText value="#{bookitem.publisher}"/>               
                            </div>
                            <div>
                                <h:commandButton value="Book Info" action="#{booksController.read(bookitem)}"/>
                            </div>
                        </div>
                    </ui:repeat>
                </div>
            </div>
        </h:form>
    </h:body>
</html>

FIT5042_Ass2-war/web/loan.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
    </h:body>
</html>

FIT5042_Ass2-war/web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
    </h:body>
</html>

FIT5042_Ass2-war/web/markedbooks.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
    </h:body>
</html>

FIT5042_Ass2-war/web/news.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
    </h:body>
</html>

FIT5042_Ass2-war/web/regisit.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
    </h:body>
</html>